-- ============================================================
-- HUAY GO — Database Schema (PostgreSQL / Supabase)
-- Deliberate 1:1 mirror of db/schema.sql's data model & conventions:
--   - datetime columns stay TEXT in 'YYYY-MM-DD HH:MM:SS' local (Asia/Bangkok) format,
--     matching every existing string-comparison/substr()/date()-prefix query in the app.
--   - boolean-ish columns stay INTEGER (0/1), matching every existing `= 1`/`= 0` query
--     and JS-side 0/1 param binding — no app code needed to change for this port.
--   - REAL -> DOUBLE PRECISION (both IEEE 754 8-byte float, closest behavioral match;
--     avoids NUMERIC's string-typed driver return values).
-- Helper functions now_local()/now_local_ts() (see db/pgHelpers.sql) provide the
-- equivalent of SQLite's datetime('now','localtime').
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT    UNIQUE NOT NULL,
  password_hash TEXT    NOT NULL,
  display_name  TEXT    NOT NULL,
  balance       DOUBLE PRECISION NOT NULL DEFAULT 0,
  credit_limit  DOUBLE PRECISION NOT NULL DEFAULT 0,
  role          TEXT    NOT NULL DEFAULT 'member' CHECK (role IN ('admin','member')),
  active        INTEGER NOT NULL DEFAULT 1,
  is_dev        INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT    NOT NULL DEFAULT now_local(),
  updated_at    TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS licenses (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  license_key       TEXT    NOT NULL UNIQUE,
  status            TEXT    NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','expired')),
  is_lifetime       INTEGER NOT NULL DEFAULT 0,
  expires_at        TEXT,
  integrity_hash    TEXT    NOT NULL,
  last_verified_at  TEXT    NOT NULL DEFAULT now_local(),
  created_by        INTEGER REFERENCES users(id),
  created_at        TEXT    NOT NULL DEFAULT now_local(),
  updated_at        TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_licenses_user ON licenses(user_id);

CREATE TABLE IF NOT EXISTS license_events (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_id    INTEGER NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,
  actor_user_id INTEGER REFERENCES users(id),
  action        TEXT    NOT NULL,
  detail        TEXT,
  created_at    TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_license_events_license ON license_events(license_id, created_at DESC);

-- lottery_types.name gets a UNIQUE constraint (absent in the SQLite original — see
-- docs/migration/phase2-notes.md) so ON CONFLICT (name) DO NOTHING in market.routes.ts
-- actually dedupes, closing a latent race where two concurrent requests could insert
-- duplicate rows for the same market name.
CREATE TABLE IF NOT EXISTS lottery_types (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL UNIQUE,
  category    TEXT    NOT NULL CHECK (category IN ('หวยไทย','หวยต่างประเทศ','หวยชุดนาน','หวยหุ้น')),
  close_time  TEXT,
  result_time TEXT,
  result_url  TEXT,
  flag_code   TEXT,
  bet_types   TEXT    NOT NULL DEFAULT '["3ตัวบน","3ตัวโต๊ด","2ตัวบน","2ตัวล่าง","วิ่งบน","วิ่งล่าง"]',
  pay_rates   TEXT    NOT NULL DEFAULT '{"3ตัวบน":500,"3ตัวโต๊ด":100,"2ตัวบน":90,"2ตัวล่าง":90,"วิ่งบน":3,"วิ่งล่าง":4}',
  active      INTEGER NOT NULL DEFAULT 1,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lottery_rounds (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lottery_type_id  INTEGER NOT NULL REFERENCES lottery_types(id),
  draw_date        TEXT    NOT NULL,
  status           TEXT    NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed','resulted')),
  result_3top      TEXT,
  result_2top      TEXT,
  result_2bot      TEXT,
  closed_at        TEXT,
  resulted_at      TEXT,
  created_at       TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS group_pay_rates (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name   TEXT    NOT NULL,
  bet_type     TEXT    NOT NULL,
  pay_rate     DOUBLE PRECISION NOT NULL,
  discount     DOUBLE PRECISION NOT NULL,
  min_bet      DOUBLE PRECISION NOT NULL DEFAULT 1,
  max_bet      DOUBLE PRECISION NOT NULL DEFAULT 100000,
  UNIQUE(group_name, bet_type)
);

CREATE TABLE IF NOT EXISTS bets (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER REFERENCES users(id),
  round_id        INTEGER NOT NULL REFERENCES lottery_rounds(id),
  bet_type        TEXT    NOT NULL,
  number          TEXT    NOT NULL,
  amount          DOUBLE PRECISION NOT NULL CHECK (amount > 0),
  pay_rate        DOUBLE PRECISION NOT NULL,
  discount_rate   DOUBLE PRECISION NOT NULL DEFAULT 0,
  win_amount      DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  status          TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','win','lose','cancelled','refunded')),
  customer_name   TEXT    NOT NULL DEFAULT '',
  paid            INTEGER NOT NULL DEFAULT 0,
  deposit_paid    INTEGER NOT NULL DEFAULT 0,
  note            TEXT    NOT NULL DEFAULT '',
  created_at      TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS transactions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id),
  type          TEXT    NOT NULL CHECK (type IN ('deposit','withdraw','bet','win','refund','adjust')),
  amount        DOUBLE PRECISION NOT NULL,
  balance_after DOUBLE PRECISION NOT NULL,
  reference_id  INTEGER,
  description   TEXT,
  created_at    TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_rounds_date        ON lottery_rounds(draw_date);
CREATE INDEX IF NOT EXISTS idx_rounds_type_date   ON lottery_rounds(lottery_type_id, draw_date);
CREATE INDEX IF NOT EXISTS idx_bets_user          ON bets(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_bets_round         ON bets(round_id);
CREATE INDEX IF NOT EXISTS idx_bets_round_status  ON bets(round_id, status);
CREATE INDEX IF NOT EXISTS idx_bets_user_status   ON bets(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bets_customer_name ON bets(customer_name, status);
CREATE INDEX IF NOT EXISTS idx_bets_created_date  ON bets(substr(created_at, 1, 10));
CREATE INDEX IF NOT EXISTS idx_txn_user           ON transactions(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_txn_user_type      ON transactions(user_id, type, created_at DESC);

CREATE TABLE IF NOT EXISTS lottery_results (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market_id    TEXT    NOT NULL,
  market_title TEXT    NOT NULL,
  group_title  TEXT    NOT NULL,
  group_sort   INTEGER NOT NULL DEFAULT 0,
  market_sort  INTEGER NOT NULL DEFAULT 0,
  draw_date    TEXT    NOT NULL,
  result_3top  TEXT,
  result_2top  TEXT,
  result_2bot  TEXT,
  image_icon   TEXT,
  status       TEXT    NOT NULL DEFAULT 'Paid',
  synced_at    TEXT    NOT NULL DEFAULT now_local(),
  UNIQUE(market_id, draw_date)
);

CREATE INDEX IF NOT EXISTS idx_lresults_date  ON lottery_results(draw_date);
CREATE INDEX IF NOT EXISTS idx_lresults_group ON lottery_results(group_title, draw_date);
CREATE INDEX IF NOT EXISTS idx_results_market  ON lottery_results(market_title, draw_date DESC);

CREATE TABLE IF NOT EXISTS daily_stats (
  date            TEXT PRIMARY KEY,
  bet_count       INTEGER NOT NULL DEFAULT 0,
  total_bet       DOUBLE PRECISION NOT NULL DEFAULT 0,
  paid_out        DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount        DOUBLE PRECISION NOT NULL DEFAULT 0,
  balance         DOUBLE PRECISION NOT NULL DEFAULT 0,
  win_count       INTEGER NOT NULL DEFAULT 0,
  lose_count      INTEGER NOT NULL DEFAULT 0,
  customer_count  INTEGER NOT NULL DEFAULT 0,
  captured_at     TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS reset_log (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reset_at  TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_reset_log_at ON reset_log(reset_at DESC);

CREATE TABLE IF NOT EXISTS line_submissions (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_user_id      TEXT    NOT NULL,
  line_display_name TEXT,
  source_type       TEXT    NOT NULL CHECK (source_type IN ('text','image')),
  raw_text          TEXT,
  image_path        TEXT,
  ocr_text          TEXT,
  ocr_confidence    DOUBLE PRECISION,
  customer_name     TEXT    NOT NULL DEFAULT '',
  status            TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  reviewed_by       INTEGER REFERENCES users(id),
  reviewed_at       TEXT,
  reject_reason     TEXT,
  deleted           INTEGER NOT NULL DEFAULT 0,
  deleted_by        TEXT,
  deleted_at        TEXT,
  payment_status            TEXT,
  payment_qr_token          TEXT,
  payment_qr_sent_at        TEXT,
  payment_hold_at           TEXT,
  payment_slip_image_path   TEXT,
  payment_confirmed_by      INTEGER REFERENCES users(id),
  payment_confirmed_at      TEXT,
  payment_cancelled_at      TEXT,
  payment_qr_user_id        INTEGER REFERENCES users(id),
  created_at        TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_line_sub_status ON line_submissions(status, created_at DESC);

CREATE TABLE IF NOT EXISTS line_submission_items (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id   INTEGER NOT NULL REFERENCES line_submissions(id) ON DELETE CASCADE,
  lottery_name    TEXT,
  bet_type        TEXT,
  number          TEXT,
  amount          DOUBLE PRECISION,
  confidence      TEXT    NOT NULL DEFAULT 'low' CHECK (confidence IN ('low','medium','high')),
  bet_id          INTEGER REFERENCES bets(id),
  created_at      TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_line_items_submission ON line_submission_items(submission_id);

CREATE TABLE IF NOT EXISTS line_conversation_state (
  line_user_id  TEXT    PRIMARY KEY,
  step          TEXT    NOT NULL DEFAULT 'idle'
                CHECK (step IN ('idle','awaiting_category','awaiting_lottery','awaiting_bet')),
  category      TEXT,
  lottery_name  TEXT,
  market_id     TEXT,
  loop_count    INTEGER NOT NULL DEFAULT 0,
  current_submission_id INTEGER,
  awaiting_payment_submission_id INTEGER,
  updated_at    TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS payment_settings (
  user_id            INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  promptpay_id_type  TEXT    NOT NULL DEFAULT 'phone' CHECK (promptpay_id_type IN ('phone','citizen_id')),
  promptpay_id       TEXT    NOT NULL DEFAULT '',
  bank_name          TEXT    NOT NULL DEFAULT '',
  account_first_name TEXT    NOT NULL DEFAULT '',
  account_last_name  TEXT    NOT NULL DEFAULT '',
  updated_at         TEXT    NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS order_search_log (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id INTEGER NOT NULL REFERENCES users(id),
  query         TEXT    NOT NULL,
  found         INTEGER NOT NULL DEFAULT 0,
  submission_id INTEGER,
  searched_at   TEXT    NOT NULL DEFAULT now_local()
);

CREATE INDEX IF NOT EXISTS idx_order_search_log_at ON order_search_log(searched_at);

CREATE TABLE IF NOT EXISTS archived_dates (
  date        TEXT PRIMARY KEY,
  archived_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_archived_date ON archived_dates(date);
