-- ============================================================
-- Postgres additive migrations — runs every boot, after postgresSchema.sql
-- Mirrors the SQLite migration block in db/index.ts (Phase 3: shops retrofit).
-- Unlike SQLite, Postgres supports ADD COLUMN IF NOT EXISTS and proper
-- ALTER COLUMN / constraint changes directly — no table-rebuild dance needed.
-- Idempotent: every statement safe to re-run on every boot.
-- ============================================================

CREATE TABLE IF NOT EXISTS shops (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT UNIQUE NOT NULL,
  name       TEXT NOT NULL,
  mode       TEXT NOT NULL DEFAULT 'offline' CHECK (mode IN ('offline','online')),
  status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended')),
  created_at TEXT NOT NULL DEFAULT now_local(),
  updated_at TEXT NOT NULL DEFAULT now_local()
);

ALTER TABLE shops ADD COLUMN IF NOT EXISTS expires_at TEXT;

CREATE TABLE IF NOT EXISTS shop_line_channels (
  shop_id            INTEGER PRIMARY KEY REFERENCES shops(id) ON DELETE CASCADE,
  channel_id         TEXT,
  channel_secret_enc TEXT,
  access_token_enc   TEXT,
  updated_at         TEXT NOT NULL DEFAULT now_local()
);

CREATE TABLE IF NOT EXISTS customers (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id      INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  line_user_id TEXT,
  display_name TEXT,
  phone        TEXT,
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT now_local(),
  UNIQUE(shop_id, line_user_id)
);
CREATE INDEX IF NOT EXISTS idx_customers_shop ON customers(shop_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE bets ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE line_submissions ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE payment_settings ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE reset_log ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
ALTER TABLE order_search_log ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);

-- ── ร้าน 1 จากข้อมูลเดิม + backfill (ต้องมาก่อนตารางที่จะทำ PK เป็น composite ด้านล่าง) ──
INSERT INTO shops (id, slug, name, mode, status)
SELECT 1, 'shop-1', 'ร้านหลัก', 'offline', 'active'
WHERE NOT EXISTS (SELECT 1 FROM shops WHERE id = 1);

SELECT setval('shops_id_seq', GREATEST((SELECT MAX(id) FROM shops), 1), true);

-- dev account (is_dev=1) เป็น platform-level ไม่ผูกร้านไหน
UPDATE users SET shop_id = 1 WHERE shop_id IS NULL AND is_dev = 0;
UPDATE bets SET shop_id = 1 WHERE shop_id IS NULL;
UPDATE transactions SET shop_id = 1 WHERE shop_id IS NULL;
UPDATE line_submissions SET shop_id = 1 WHERE shop_id IS NULL;
UPDATE payment_settings SET shop_id = 1 WHERE shop_id IS NULL;
UPDATE reset_log SET shop_id = 1 WHERE shop_id IS NULL;
UPDATE order_search_log SET shop_id = 1 WHERE shop_id IS NULL;

-- ── ตารางที่ PK ต้องเปลี่ยนเป็น composite (shop_id, ...) — Postgres ทำตรงๆ ได้ ไม่ต้อง rebuild ──
ALTER TABLE daily_stats ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
UPDATE daily_stats SET shop_id = 1 WHERE shop_id IS NULL;
ALTER TABLE daily_stats ALTER COLUMN shop_id SET NOT NULL;
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint WHERE conrelid = 'daily_stats'::regclass AND contype = 'p';
  IF cname IS NOT NULL AND cname != 'daily_stats_shop_pkey' THEN
    EXECUTE format('ALTER TABLE daily_stats DROP CONSTRAINT %I', cname);
    ALTER TABLE daily_stats ADD CONSTRAINT daily_stats_shop_pkey PRIMARY KEY (shop_id, date);
  END IF;
END $$;

ALTER TABLE archived_dates ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
UPDATE archived_dates SET shop_id = 1 WHERE shop_id IS NULL;
ALTER TABLE archived_dates ALTER COLUMN shop_id SET NOT NULL;
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint WHERE conrelid = 'archived_dates'::regclass AND contype = 'p';
  IF cname IS NOT NULL AND cname != 'archived_dates_shop_pkey' THEN
    EXECUTE format('ALTER TABLE archived_dates DROP CONSTRAINT %I', cname);
    ALTER TABLE archived_dates ADD CONSTRAINT archived_dates_shop_pkey PRIMARY KEY (shop_id, date);
  END IF;
END $$;

ALTER TABLE line_conversation_state ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
UPDATE line_conversation_state SET shop_id = 1 WHERE shop_id IS NULL;
ALTER TABLE line_conversation_state ALTER COLUMN shop_id SET NOT NULL;
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint WHERE conrelid = 'line_conversation_state'::regclass AND contype = 'p';
  IF cname IS NOT NULL AND cname != 'line_conversation_state_shop_pkey' THEN
    EXECUTE format('ALTER TABLE line_conversation_state DROP CONSTRAINT %I', cname);
    ALTER TABLE line_conversation_state ADD CONSTRAINT line_conversation_state_shop_pkey PRIMARY KEY (shop_id, line_user_id);
  END IF;
END $$;

-- group_pay_rates: UNIQUE(group_name, bet_type) -> UNIQUE(shop_id, group_name, bet_type)
ALTER TABLE group_pay_rates ADD COLUMN IF NOT EXISTS shop_id INTEGER REFERENCES shops(id);
UPDATE group_pay_rates SET shop_id = 1 WHERE shop_id IS NULL;
ALTER TABLE group_pay_rates ALTER COLUMN shop_id SET NOT NULL;
DO $$
DECLARE cname text;
BEGIN
  SELECT conname INTO cname FROM pg_constraint
    WHERE conrelid = 'group_pay_rates'::regclass AND contype = 'u'
    AND conname != 'group_pay_rates_shop_unique';
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE group_pay_rates DROP CONSTRAINT %I', cname);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conrelid = 'group_pay_rates'::regclass AND conname = 'group_pay_rates_shop_unique'
  ) THEN
    ALTER TABLE group_pay_rates ADD CONSTRAINT group_pay_rates_shop_unique UNIQUE(shop_id, group_name, bet_type);
  END IF;
END $$;

-- Phase 5: LIFF ลูกค้าแทงเอง — bets.user_id ผ่อนเป็น nullable + เพิ่ม customer_id
-- (โพยที่ staff คีย์มี user_id, โพยที่ลูกค้าแทงเองผ่าน LIFF มี customer_id — ต้องมีเป๊ะ 1 ใน 2)
ALTER TABLE bets ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES customers(id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conrelid = 'bets'::regclass AND conname = 'bets_user_or_customer_chk'
  ) THEN
    ALTER TABLE bets ADD CONSTRAINT bets_user_or_customer_chk
      CHECK ((user_id IS NOT NULL AND customer_id IS NULL) OR (user_id IS NULL AND customer_id IS NOT NULL));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_bets_customer_id ON bets(customer_id, status, created_at DESC);

-- Phase 6: subscription lifecycle — plan + expires_at drive auto-suspend (subscription.service.ts)
-- TEXT + CHECK (not ENUM) to mirror the SQLite side exactly — same values, no ALTER TYPE migrations later.
ALTER TABLE shops ADD COLUMN IF NOT EXISTS plan TEXT;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conrelid = 'shops'::regclass AND conname = 'shops_plan_chk'
  ) THEN
    ALTER TABLE shops ADD CONSTRAINT shops_plan_chk CHECK (plan IN ('free','monthly','annual') OR plan IS NULL);
  END IF;
END $$;

-- Phase 6: manual payment ledger — mirrors the SQLite table in db/index.ts exactly
CREATE TABLE IF NOT EXISTS shop_payments (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id      INTEGER NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
  amount       REAL    NOT NULL CHECK (amount > 0),
  period       TEXT    NOT NULL CHECK (period IN ('monthly','annual')),
  note         TEXT,
  recorded_by  INTEGER REFERENCES users(id),
  created_at   TEXT    NOT NULL DEFAULT now_local()
);
CREATE INDEX IF NOT EXISTS idx_shop_payments_shop ON shop_payments(shop_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shop_payments_created ON shop_payments(created_at DESC);

-- ── ที่มาของโพย (dashboard admin แยก LIFF/LINE/หน้าร้าน) — mirror ของ migration ใน db/index.ts
ALTER TABLE bets ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'web';
UPDATE bets SET source = 'liff' WHERE source = 'web' AND customer_id IS NOT NULL;
UPDATE bets SET source = 'line' WHERE source = 'web' AND note LIKE '%LINE%';

-- LIFF Home tab: ประกาศ/โปรโมชั่นต่อร้าน — mirror ของ migration ใน db/index.ts
CREATE TABLE IF NOT EXISTS shop_announcements (
  shop_id    INTEGER PRIMARY KEY REFERENCES shops(id) ON DELETE CASCADE,
  message    TEXT    NOT NULL DEFAULT '',
  active     INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT    NOT NULL DEFAULT now_local()
);

-- LIFF Settings tab: อีเมล (แก้ไขเองได้) — mirror ของ migration ใน db/index.ts
ALTER TABLE customers ADD COLUMN IF NOT EXISTS email TEXT;
